apply plugin: 'com.android.application'

android {
    defaultConfig {
        applicationId "net.simplr.woosimdp230l"
        minSdkVersion 21
        compileSdk 33
        targetSdkVersion 33
        versionCode 10
        versionName "2.0"

        testInstrumentationRunner "androidx.test.runner.AndroidJUnitRunner"
    }

    buildTypes {
        release {
            minifyEnabled false
            proguardFiles getDefaultProguardFile('proguard-android-optimize.txt'), 'proguard-rules.pro'
        }
    }
    compileOptions {
        sourceCompatibility JavaVersion.VERSION_1_8
        targetCompatibility JavaVersion.VERSION_1_8
    }
    buildFeatures {
        viewBinding true
    }
    namespace 'net.simplr.woosimdp230l'
}

dependencies {
//    implementation fileTree(dir: "libs", include: ["*.jar", "*.aar"])
    implementation 'androidx.appcompat:appcompat:1.6.1'
    implementation 'androidx.constraintlayout:constraintlayout:2.1.4'
    implementation files('libs/dascom2.5.4.6620.jar')
    implementation files('libs/ZSDK_ANDROID_API.jar')
    implementation files('libs/WoosimLib261.jar')
    implementation files('libs/oneil_lib_2.4.9.aar')
    implementation 'com.google.zxing:core:3.5.3'
    implementation 'com.github.DantSu:ESCPOS-ThermalPrinter-Android:3.3.0'
    implementation 'com.guolindev.permissionx:permissionx:1.7.1'
    implementation 'com.sunmi:printerlibrary:1.0.18'
    implementation 'com.afollestad:recyclical:1.1.1'
    def lottieVersion = "4.2.2"
    implementation "com.airbnb.android:lottie:$lottieVersion"
}